apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: l6p:system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: l6p:system
subjects:
  - kind: ServiceAccount
    name: {{ include "server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.engineNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: l6p:system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: l6p:system
subjects:
  - kind: ServiceAccount
    name: {{ include "server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.engineNamespace }}
  name: l6p:space
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: l6p:space
subjects:
  - kind: ServiceAccount
    name: {{ include "server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
